Lab1
dikareva-me/Operating-systems pull request #1
Opened 2023-10-27 19:37 UTC by dikareva-me

2023-10-28 12:10 UTC, DariaWelt requested changes
Демон запустился в 1 раз с неправильным конфигом и показал ошибку(что хорошо)
При повторном запуске с поправленным конфигом  демон не может прочитать pid-файл.
```
root@Ubuntu:/home/vboxuser/os_labs/dikareva-me/Lab1# journalctl -t daemonlab1
okt 28 13:47:11 Ubuntu daemonlab1[6674]: Initializing daemon
okt 28 13:47:11 Ubuntu daemonlab1[6674]: Home directory - /home/vboxuser/os_labs/dikareva-me/Lab1
okt 28 13:47:11 Ubuntu daemonlab1[6674]: Starting init thread...
okt 28 13:47:11 Ubuntu daemonlab1[6676]: Handle PID file...
okt 28 13:47:11 Ubuntu daemonlab1[6676]: Saving pid file...
okt 28 13:47:11 Ubuntu daemonlab1[6676]: Thread init complete
okt 28 13:47:11 Ubuntu daemonlab1[6676]: Signals initialization
okt 28 13:47:11 Ubuntu daemonlab1[6676]: Trying read config file - /home/vboxuser/os_labs/dikareva-me/Lab1/con>
okt 28 13:47:11 Ubuntu daemonlab1[6676]: Parsing config file...
okt 28 13:47:11 Ubuntu daemonlab1[6676]: DONE
okt 28 13:47:11 Ubuntu daemonlab1[6676]: ERROR:: ERROR: Couldn't find path:test_dir/logs
okt 28 13:55:50 Ubuntu daemonlab1[6988]: Initializing daemon
okt 28 13:55:50 Ubuntu daemonlab1[6988]: Home directory - /home/vboxuser/os_labs/dikareva-me/Lab1
okt 28 13:55:50 Ubuntu daemonlab1[6988]: Starting init thread...
okt 28 13:55:50 Ubuntu daemonlab1[6990]: Handle PID file...
okt 28 13:55:50 Ubuntu daemonlab1[6990]: ERROR:: ERROR: Can't open pid file
okt 28 13:56:52 Ubuntu daemonlab1[7003]: Initializing daemon
okt 28 13:56:52 Ubuntu daemonlab1[7003]: Home directory - /home/vboxuser/os_labs/dikareva-me/Lab1
okt 28 13:56:52 Ubuntu daemonlab1[7003]: Starting init thread...
okt 28 13:56:52 Ubuntu daemonlab1[7005]: Handle PID file...
okt 28 13:56:52 Ubuntu daemonlab1[7005]: ERROR:: ERROR: Can't open pid file
```
В остальном всё работает хорошо

2023-10-28 12:10 UTC, DariaWelt commented on Lab1/daemon/Daemon.cpp
> +    char *result = realpath(output.c_str(), nullptr);
Лучше пользоваться умными указателями

2023-10-28 12:10 UTC, DariaWelt commented on Lab1/daemon/Daemon.cpp
> +bool Daemon::initTread() const{
Название неправильное. Thread - это поток, а не процесс

2023-10-29 15:02 UTC, dikareva-me commented
> Демон запустился в 1 раз с неправильным конфигом и показал ошибку(что хорошо) При повторном запуске с поправленным конфигом демон не может прочитать pid-файл.
> 
> ```
> root@Ubuntu:/home/vboxuser/os_labs/dikareva-me/Lab1# journalctl -t daemonlab1
> okt 28 13:47:11 Ubuntu daemonlab1[6674]: Initializing daemon
> okt 28 13:47:11 Ubuntu daemonlab1[6674]: Home directory - /home/vboxuser/os_labs/dikareva-me/Lab1
> okt 28 13:47:11 Ubuntu daemonlab1[6674]: Starting init thread...
> okt 28 13:47:11 Ubuntu daemonlab1[6676]: Handle PID file...
> okt 28 13:47:11 Ubuntu daemonlab1[6676]: Saving pid file...
> okt 28 13:47:11 Ubuntu daemonlab1[6676]: Thread init complete
> okt 28 13:47:11 Ubuntu daemonlab1[6676]: Signals initialization
> okt 28 13:47:11 Ubuntu daemonlab1[6676]: Trying read config file - /home/vboxuser/os_labs/dikareva-me/Lab1/con>
> okt 28 13:47:11 Ubuntu daemonlab1[6676]: Parsing config file...
> okt 28 13:47:11 Ubuntu daemonlab1[6676]: DONE
> okt 28 13:47:11 Ubuntu daemonlab1[6676]: ERROR:: ERROR: Couldn't find path:test_dir/logs
> okt 28 13:55:50 Ubuntu daemonlab1[6988]: Initializing daemon
> okt 28 13:55:50 Ubuntu daemonlab1[6988]: Home directory - /home/vboxuser/os_labs/dikareva-me/Lab1
> okt 28 13:55:50 Ubuntu daemonlab1[6988]: Starting init thread...
> okt 28 13:55:50 Ubuntu daemonlab1[6990]: Handle PID file...
> okt 28 13:55:50 Ubuntu daemonlab1[6990]: ERROR:: ERROR: Can't open pid file
> okt 28 13:56:52 Ubuntu daemonlab1[7003]: Initializing daemon
> okt 28 13:56:52 Ubuntu daemonlab1[7003]: Home directory - /home/vboxuser/os_labs/dikareva-me/Lab1
> okt 28 13:56:52 Ubuntu daemonlab1[7003]: Starting init thread...
> okt 28 13:56:52 Ubuntu daemonlab1[7005]: Handle PID file...
> okt 28 13:56:52 Ubuntu daemonlab1[7005]: ERROR:: ERROR: Can't open pid file
> ```
> 
> В остальном всё работает хорошо

Возможно это было из-за отсутствия тестовых папок. Добавила их, у меня работает без этой ошибки даже если сначала передавать неправильное название конфига, а потом правильное.

```

Oct 29 17:53:11 Ubuntu daemonlab1[6805]: Initializing daemon
Oct 29 17:53:11 Ubuntu daemonlab1[6805]: Home directory - /home/user1/Downloads/Lab1(1)/Lab1
Oct 29 17:53:11 Ubuntu daemonlab1[6805]: Starting init thread...
Oct 29 17:53:11 Ubuntu daemonlab1[6808]: Handle PID file...
Oct 29 17:53:11 Ubuntu daemonlab1[6506]: Handle signal 15
Oct 29 17:53:11 Ubuntu daemonlab1[6506]: Terminate daemon
Oct 29 17:53:11 Ubuntu daemonlab1[6808]: Saving pid file...
Oct 29 17:53:11 Ubuntu daemonlab1[6808]: Thread init complete
Oct 29 17:53:11 Ubuntu daemonlab1[6808]: Signals initialization
Oct 29 17:53:11 Ubuntu daemonlab1[6808]: ERROR:: ERROR: Couldn't find path:conf
Oct 29 17:53:39 Ubuntu daemonlab1[6881]: Initializing daemon
Oct 29 17:53:39 Ubuntu daemonlab1[6881]: Home directory - /home/user1/Documents/operating-systems/Lab1
Oct 29 17:53:39 Ubuntu daemonlab1[6881]: Starting init thread...
Oct 29 17:53:39 Ubuntu daemonlab1[6884]: Handle PID file...
Oct 29 17:53:39 Ubuntu daemonlab1[6884]: Saving pid file...
Oct 29 17:53:39 Ubuntu daemonlab1[6884]: Thread init complete
Oct 29 17:53:39 Ubuntu daemonlab1[6884]: Signals initialization
Oct 29 17:53:39 Ubuntu daemonlab1[6884]: Trying read config file - /home/user1/Documents/operating-systems/Lab1/config.txt
Oct 29 17:53:39 Ubuntu daemonlab1[6884]: Parsing config file...
Oct 29 17:53:39 Ubuntu daemonlab1[6884]: DONE
Oct 29 17:53:39 Ubuntu daemonlab1[6884]: Daemon is successfully initialized
```

2023-11-01 17:48 UTC, DariaWelt requested changes
Уберите, пожалуйста свои тестовые папки. Мой комментарий касался случая, когда в существующем файле конфига лежат несуществующие пути. Это и называется невалидный конфиг

2023-11-02 18:36 UTC, DariaWelt approved these changes
Работа зачтена

2023-11-04 12:48 UTC, merged