Lab2
dikareva-me/Operating-systems pull request #2
Opened 2023-11-26 20:01 UTC by dikareva-me

Дикарева Мария, вариант 15: 

Независимые. Один к одному. 2, 4, 6

2023-11-29 21:47 UTC, DariaWelt requested changes

2023-11-29 21:47 UTC, DariaWelt commented on Lab2/src/client/clientHandler.cpp
> +    std::future<std::string> future = std::async(getFromTerminal);
Этими функциями пользоваться нельзя. И не очень понятно зачем вообще это нужно если в следующей строчке вы фактически джоин делаете

2023-11-29 21:47 UTC, DariaWelt commented on Lab2/src/client/clientHandler.cpp
> +    std::thread connectionThread(&Client::processConn, this);
Нельзя пользоваться std многопоточностью

2023-12-03 13:28 UTC, dikareva-me commented
Здравствуйте! Хочу воспользоваться предложенной возможностью сдать работу с std многопоточностью и async на 80% баллов, как обсуждалось в телеграм канале.

2023-12-09 12:06 UTC, DariaWelt commented
работа зачтена

2023-12-09 12:06 UTC, merged